backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: https://github.com/webdigga/ear-protectors
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "article"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also determines the URL (between 20 and 70 characters)*",
        pattern: ['^.{20,70}$', "Must be between 20 and 70 characters"]
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters)*",
        pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (between 50 and 155 characters)*",
        pattern: ['^.{50,155}$', "Must be between 50 and 155 characters"]
      }
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "latestNews", "privacy"]
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "latestNews", "privacy", "faq"]
      - { label: "In the media and accreditations copy", name: "inTheMediaAndAccreditationsCopy", widget: "string", required: false }
      - label: "YouTube video path"
        name: "youTubeVideos"
        widget: "list"
        fields:
          - { label: "Video title", name: "videoTitle", widget: "string" }
          - { label: "Embed path", name: "embedPath", widget: "string" }
      - label: "Accreditation images"
        name: "accreditationImages"
        widget: "list"        
        fields:
          - label: Accreditation image
            name: accreditationImage
            widget: object
            fields:
              - { label: Image Alt, name: imageAlt, widget: string }
              - { label: Image, name: image, widget: image }
      - label: "Highlights box"
        name: "highlightsBoxes"
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Highlights list item
            name: highlightsListItem
            widget: list
            fields:
              - { label: Highlight, name: highlight, widget: string }
  - label: "Landing page"
    name: "landingPage"
    folder: "src/landing"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      - label: "Highlights box"
        name: "highlightsBoxes"
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Highlights list item
            name: highlightsListItem
            widget: list
            fields:
              - { label: Highlight, name: highlight, widget: string }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["landing"]
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["landing"]
  - label: "ProductCard"
    name: "productCard"
    folder: "src/productCards"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Article Link", name: "articleLink", widget: "string" }
      - { label: "Image Alt", name: "imageAlt", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
      - { label: "Order", name: "order", widget: "number" }
  - label: "Hero"
    name: "hero"
    folder: "src/hero"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Introduction Text", name: "introText", widget: "text" }
      - { label: "Button text", name: "buttonText", widget: "string" }
      - { label: "Button URL", name: "buttonUrl", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
  - label: "Homepage spiel"
    name: "homepageSpiel"
    folder: "src/homepageSpiel"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Show in Primary Nav?, name: showInPrimary, widget: boolean }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - {
            label: Title,
            name: title,
            widget: string
          }
          - {
            label: SEO Title,
            name: seoTitle,
            widget: string,
            hint: "*This title will be used in the title tag for search engines (between 50 and 60 characters)*",
            pattern: ['^.{50,60}$', "Must be between 50 and 60 characters"]
          }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - {
            label: Description,
            name: description,
            widget: string,
            hint: "*Used in search engines (more than 70 characters and less than 155 characters)*"
          }
          - { label: Type (type of template), name: type, widget: string }
          - { label: Logo (Alt), name: logoAlt, widget: string }
          - label: "Logo (URL)"
            name: "logoUrl"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
  - label: "FAQs"
    name: "faqs"
    editor:
      preview: false
    files:
      - label: "FAQs items"
        name: "faqs"
        file: "src/_data/faqsData.yaml"
        fields:
          - label: FAQ Items
            name: faqs
            widget: list
            collapsed: false
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }